### ISSUE TITLE
on sequelizeHandlers.get(Model) return TypeError: Cannot set property 'id' of undefined

### ISSUE THREAD

**Issue by chameleonbr** [botter-workshop/sequelize-handlers#1]
I tried to get model using GET /users/:id and returned error:
TypeError: Cannot set property 'id' of undefined
    a t.../node_modules/sequelize-handlers/handlers/get.js:7:53
I have changed handlers/get.js to:

``` javascript
var options = req.options || {};; 
//added code below
options["where"] = {};
options["where"][model.primaryKeyAttribute] = req.params.id;
```

And worked fine.

**Comment by benthepoet** [comment]
Thanks, I missed that. I'll add that safety in so it doesn't happen anymore.
