### ISSUE TITLE
Error middleware

### ISSUE THREAD

**Issue by victorlm125** [botter-workshop/sequelize-handlers#11]
Cannot put middleware before send data so I can't to examine data before has sent. I need examine to decide if I must to broadcast data throught websocket.

The middleware is never called.

This is a example I am using the library:

const modelNameHandler = new ModelHandler(global.db[modelName]);
app.get('/' + endpoint + version + modelName + 's/:id', modelNameHandler.get());

**Comment by benthepoet** [comment]
Note there's no way to prevent the data from sending, but there is an undocumented feature you can use to access the data before the response has been sent. Simply override `res.transform` in a middleware before the handler. The handler calls the `res.transform` function to manipulate the data before it is sent back. 

```javascript
const modelHandler = new ModelHandler(Something);
app.get('/something', function (req, res, next) {
  res.transform = function (data) { 
    console.log(data);
    return data;
  };
  next();
}, modelHandler.get());
```

**Comment by victorlm125** [comment]
Hi,

Thanks very much for the advice. It running ok. On the other hand, I would know when you release a versión with a ‘include’ (in order to recover tables with associations) and if it will be possible to use ‘fileds’ option with the associate table.

Thanks in advance,
Víctor

Enviado desde Correo para Windows 10

De: Ben Hanna
Enviado: miércoles, 13 de diciembre de 2017 15:25
Para: botter-workshop/sequelize-handlers
CC: victorlm125; Author
Asunto: Re: [botter-workshop/sequelize-handlers] Error middleware (#11)

Note there's no way to prevent the data from sending, but there is an undocumented feature you can use to access the data before the response has been sent. Simply override res.transform in a middleware before the handler. The handler calls the res.transform function to manipulate the data before it is sent back.
const modelHandler = new ModelHandler(Something);
app.get('/something', function (req, res, next) {
  res.transform = function (data) { 
    console.log(data);
    return data;
  };
  next();
}, modelHandler.get());

**Comment by benthepoet** [comment]
Currently, I don't have any plans to release a version that allows for including associations. Nested data is a pattern I try to avoid in REST APIs, and as such I usually model associations as separate resources. I'd recommend looking into using GraphQL if you want a means of fetching your data with nested associations.
